# Generated by Django 5.0.6 on 2024-05-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catergories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='address',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='email',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
