# Generated by Django 5.0.6 on 2024-05-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catergories', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prosduct',
            new_name='Product',
        ),
    ]
